# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-191565417-1' 
g-TAG: 'UA-191565417-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Talking', path: 'menu', url: 'talking.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/yalematta/'}
- {icon: 'twitter', link: 'https://twitter.com/yalematta'}
- {icon: 'mastodon', link: 'https://androiddev.social/@yalematta'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/layalematta/'}
- {icon: 'youtube', link: 'https://www.youtube.com/LayaleMatta'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
